[build]
  command = "npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "openai"]
  included_files = ["node_modules/.prisma/client/**", "prisma/schema.prisma"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Route ALL requests to the actual handler name
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200
